<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GodotProjectDir>$(MSBuildProjectDirectory)/..</GodotProjectDir>
    <GodotProjectDirBase64>$([MSBuild]::ConvertToBase64('$(GodotProjectDir)'))</GodotProjectDirBase64>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <CompilerVisibleProperty Include="GodotProjectDirBase64" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../RoguelikeCrawler.csproj" />
  </ItemGroup>
</Project>
